/**
 * canvas/export.mjs — PNG screenshot and ZIP asset export.
 *
 * Public API:
 *   exportCanvasPNG()   — downloads the current canvas as a stamped PNG
 *   exportAssets()      — bundles JSON + per-slide renders + backdrops into a ZIP
 */

import JSZip from 'jszip';
import { log } from '../logger.mjs';
import { graph } from '../pipeline/graph.mjs';
import { LIBRARY } from '../pipeline/local-graph.mjs';
import { getSlideCount, getSlideIds } from './slides.mjs';
import { getRenderer, getCamera, getScene, getControls } from './scene.mjs';
import { getAllBackdrops, getCanonicalCamera } from './scene-painter.mjs';
import { getCurrentDocMeta } from './app-state.mjs';

export function exportCanvasPNG() {
  const canvas = document.querySelector('.canvas-wrap canvas');
  if (!canvas) { log('ERROR', 'no canvas found'); return; }

  const w = canvas.width, h = canvas.height;
  const overlay = document.createElement('canvas');
  overlay.width = w; overlay.height = h;
  const ctx = overlay.getContext('2d');

  ctx.drawImage(canvas, 0, 0);

  ctx.fillStyle = 'rgba(0,0,0,0.7)';
  ctx.fillRect(0, 0, w, 36);
  ctx.fillRect(0, h - 28, w, 28);

  ctx.font = 'bold 16px "IBM Plex Mono", monospace';
  ctx.fillStyle = '#ff6600';
  ctx.textBaseline = 'middle';
  ctx.fillText('kaaroViewer', 12, 18);

  const nodeCount = graph.nodes.size;
  const edgeCount = graph.edges.size;
  ctx.font = '12px "IBM Plex Mono", monospace';
  ctx.fillStyle = '#ccccaa';
  ctx.textAlign = 'right';
  ctx.fillText(`${nodeCount} nodes · ${edgeCount} edges · ${new Date().toLocaleDateString()}`, w - 12, 18);

  ctx.textAlign = 'left';
  ctx.font = '10px "IBM Plex Mono", monospace';
  ctx.fillStyle = '#667755';
  ctx.fillText('Generated by kaaroViewer — Knowledge Graph Explorer', 12, h - 10);

  const link = document.createElement('a');
  link.download = `kaaroViewer_${new Date().toISOString().slice(0, 10)}.png`;
  link.href = overlay.toDataURL('image/png');
  link.click();

  log('SYSTEM', 'PNG exported');
}

export async function exportAssets() {
  const _currentDocMeta = getCurrentDocMeta();
  if (!_currentDocMeta) { log('SYSTEM', 'no brief loaded — open a library doc first'); return; }

  const docId    = _currentDocMeta.id;
  const docTitle = _currentDocMeta.title ?? docId;
  log('SYSTEM', `asset export started for "${docTitle}"`);

  const zip = new JSZip();

  // ── manifest.json ──────────────────────────────────────────────────────────
  const slideCount = getSlideCount();
  const slideIds   = getSlideIds();
  zip.file('manifest.json', JSON.stringify({
    docId,
    title:      docTitle,
    exportedAt: new Date().toISOString(),
    nodes:      graph.nodes.size,
    edges:      graph.edges.size,
    slideCount,
    slideIds,
    ffmpegHint: `ffmpeg -framerate 1/4 -pattern_type glob -i 'slide_*_canvas.png' -c:v libx264 -pix_fmt yuv420p out.mp4`,
  }, null, 2));

  // ── doc.json ────────────────────────────────────────────────────────────────
  const libEntry = LIBRARY.find(l => l.id === docId);
  if (libEntry?.path) {
    try {
      const raw = await fetch(libEntry.path).then(r => r.text());
      zip.file('doc.json', raw);
    } catch (err) {
      log('SYSTEM', `asset export: doc.json fetch failed — ${err.message}`);
    }
  }

  // ── canvas_overview.png ────────────────────────────────────────────────────
  const renderer   = getRenderer();
  const cam        = getCamera();
  const scene      = getScene();
  const threeCanvas = document.querySelector('.canvas-wrap canvas');
  if (threeCanvas) {
    if (renderer) renderer.render(scene, cam);
    zip.file('canvas_overview.png', threeCanvas.toDataURL('image/png').split(',')[1], { base64: true });
  }

  // ── Per-slide canvas renders ───────────────────────────────────────────────
  const savedPos    = cam?.position?.clone?.();
  const savedTarget = getControls()?.target?.clone?.();

  if (renderer && cam && scene && slideCount > 0) {
    for (let i = 0; i < slideCount; i++) {
      const { pos, target } = getCanonicalCamera(i);
      cam.position.copy(pos);
      cam.lookAt(target);
      renderer.render(scene, cam);
      const dataURL = renderer.domElement.toDataURL('image/png');
      zip.file(`slide_${String(i).padStart(2, '0')}_canvas.png`, dataURL.split(',')[1], { base64: true });
    }
    if (savedPos)    { cam.position.copy(savedPos); cam.lookAt(savedTarget); }
    if (savedTarget) { getControls().target.copy(savedTarget); }
    if (renderer)    renderer.render(scene, cam);
  }

  // ── Backdrop images from IDB ───────────────────────────────────────────────
  const backdrops = await getAllBackdrops(docId);
  for (const { slideIdx, dataURL } of backdrops) {
    const base64 = dataURL.includes(',') ? dataURL.split(',')[1] : dataURL;
    zip.file(`slide_${String(slideIdx).padStart(2, '0')}_backdrop.png`, base64, { base64: true });
  }

  // ── Download ───────────────────────────────────────────────────────────────
  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } });
  const url  = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href     = url;
  link.download = `kaaroViewer-export-${docId}-${new Date().toISOString().slice(0, 10)}.zip`;
  link.click();
  URL.revokeObjectURL(url);

  log('SYSTEM', `asset export complete — ${slideCount} slides, ${backdrops.length} backdrops`);
}
